core/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('my_learning', views.learning, name='my_learning'),
    path('recommend/', views.recommend_ui, name='recommend_ui'),
    path('recommend_books/', views.recommend, name='recommend'),
    # path('face_authentication/', views.face_authentication, name='face_authentication'),
]

course_recommendation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

item/urls.py
from django.urls import path, include
from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

core/models.py
from django.db import models
# from django.contrib.auth.models import User
from item.models import Item, Category
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, username, email, password,hashed_password, **extra_fields):

        if not username:
            raise ValueError('User must have a valid username')
        if not email:
            raise ValueError('User must have a email')
        if not password:
            raise ValueError('User must have a password')
        # if not image:
        #     raise ValueError('User must have a image')
        
        user = self.model(username=username, email=self.normalize_email(email),hashed_password=hashed_password, **extra_fields)
        user.set_password(password)
        # user.is_active = True
        # user.is_staff = True
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username,email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        return self.create_user(username, email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    hashed_password = models.CharField(max_length=255)
    # image = models.ImageField(upload_to='users', null=True, blank=True)

    # Add additional fields to the user model
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email", "password"]#, "image"]
    objects = UserManager()

    def __str__(self):
        return "@{}".format(self.username)
    
class Order(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.id)
    
class Userimage(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='users', blank=False, null=False)
    
class Order_Item(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)
    buy_date = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100, null=True)

class Camera_image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='login_folder', blank=True, null=True)

# class Profile(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     preferred_category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

core/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# from django.contrib.auth.models import User
# from django.contrib.auth import get_user_model

# class LoginForm(AuthenticationForm):

#     username = forms.CharField(widget=forms.TextInput(attrs={
#         'placeholder': 'Your Username',
#         'name': 'username',
#         'class': 'w-full py-4 px-6 rounded-xl'}))

#     password = forms.CharField(widget=forms.PasswordInput(attrs={
#         'placeholder': 'Your Password',
#         'name': 'password',
#         'class': 'w-full py-4 px-6 rounded-xl'}))
    
#     img = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'id': 'img'}))

#     def clean_img(self):
#         img_data = self.cleaned_data['img']
#         if not img_data:
#             raise forms.ValidationError("Image data is required.")
#         # Additional validation logic for the image data if needed
#         return img_data

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'}), label='Username')

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'}), label='Password')
    
    # img = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'img'}))

    # def clean_img(self):
    #     img_data = self.cleaned_data['img']
    #     if not img_data:
    #         raise forms.ValidationError("Image data is required.")
    #     # Additional validation logic for the image data if needed
    #     return img_data


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    # image = forms.ImageField()

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from item.models import Category, Item
from .forms import SignupForm, LoginForm
from .models import Order, Order_Item, User
# from django.contrib.User import User
import io
from django.conf import settings
import numpy as np
import bcrypt


# Create your views here.
def index(request):
    recommended = []
    if request.user.is_authenticated:
        customer = User.objects.get(username=request.user.username)
        recommended_category = get_user_preferred_category(customer)
        if recommended_category:
        # profile = Profile.objects.get(user=customer)
        # recommended_category = profile.preferred_category
            recommended_all = Item.objects.filter(category=recommended_category)

            order = Order.objects.get(user=customer)
            items = Order_Item.objects.filter(order=order)

            for item in recommended_all:
                if item not in items:
                    recommended.append(item)
                if len(recommended)==3:
                    break

    items = Item.objects.all().order_by('price')#.values()
    categories = Category.objects.all()
    user=request.user
    a = dict()
    a['user']=user
    a['items'] = items
    a['categories'] = categories
    a['count'] = int(len(recommended))
    a['recommended'] = recommended

    return render(request, 'core/index.html', context=a)

def contact(request):
    return render(request, 'core/contact.html')

def about(request):
    return render(request, 'core/about.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            # form.save()
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            password1 = form.cleaned_data.get("password1")
            password2 = form.cleaned_data.get("password2")
            # image = form.cleaned_data.get("image")
            hash = bcrypt.hashpw(password1.encode('utf8'), bcrypt.gensalt())
            
            xyz=User(username=username,email=email,password=password1,hashed_password=hash)
            xyz.save()
            
            user = User.objects.get(username=username)
            order = Order(user=user)
            order.save()
            # print(xyz.username)
            # print(xyz.password)
            # user_img = Userimage(user=user, img=image)
            # user_img.save()
            # profile = Profile(user=user)
            # profile.save()
            # user = authenticate(username=username,password=password1)
            login(request,user)        
            return redirect('/')
        else:
            a=dict()
            a['form'] = form
            return render(request, 'core/signup.html', context=a)
        
    else:
        form = SignupForm()
        
    a=dict()
    a['form'] = form
    return render(request, 'core/signup.html', context=a)

def login_view(request):
    if request.method == 'POST':
        # if form.is_valid():
        # print(123)
        username = request.POST.get("username")
        password = request.POST.get("password")
        user1 = User.objects.get(username=username)
        print(user1.username, user1.password)
        #user = authenticate(request, username=username,password=password)
        # print(user.password)
        # if user is not None:
        if username == user1.username and password == user1.password:
                login(request, user1)
                return redirect('/')
            
        else:
            form = LoginForm()
            # form.add_error(None, 'Username and Password do not match.')
    else:
        form = LoginForm()

    return render(request, "core/login.html", {'form': form})


def logout_view(request):
    logout(request)
    return redirect('/')

def learning(request):
    if request.user.is_authenticated:
        customer = User.objects.filter(username=request.user.username)[0]
        order = Order.objects.get(user=customer)
        items = Order_Item.objects.filter(order=order)
    else:
        form = LoginForm()
        return render(request, "core/login.html", {'form': form})
    
    return render(request, 'core/cart.html', {'items': items})

def get_user_preferred_category(user):
    # try:
    #     profile = Profile.objects.get(user=user)
    # except:
    #     return 
    order = Order.objects.get(user=user)
    purchased_courses = Order_Item.objects.filter(order=order)

    # Count the occurrences of each category in purchased courses
    category_counts = {}
    for course in purchased_courses:
        category_counts[course.item.category] = category_counts.get(course.item.category, 0) + 1

    # Find the category with the maximum count
    if len(category_counts)>0:
        preferred_category = max(category_counts, key=category_counts.get)

        return preferred_category
    return False

import pickle
from django.http import HttpResponse


def initialize_app():
    popular_df = pickle.load(open('core/data/courses.pkl', 'rb'))
    similarity_scores = pickle.load(open('core/data/similarity.pkl', 'rb'))
    return popular_df, similarity_scores

popular_df, similarity_scores = initialize_app()

def recommend_ui(request):
    return render(request, 'core/recommend1.html')

def recommend(request):
    if request.method == 'GET':
        user_input = request.GET.get('user_input')
        try:
            index = popular_df[popular_df['course_name'] == user_input].index[0]
        except:
            return render(request, 'core/error.html', {'message': 'Course not found'})

        distances = sorted(list(enumerate(similarity_scores[index])), reverse=True, key=lambda x: x[1])
        data = []
        for i in distances[1:6]:
            item = []
            item.append(popular_df.iloc[i[0]].course_name)
            item.append(popular_df.iloc[i[0]].University)
            item.append(popular_df.iloc[i[0]].difficulty_level)
            item.append(popular_df.iloc[i[0]].course_rating)
            data.append(item)
        print(data)
        return render(request, 'core/recommend1.html', {'data': data})
    return HttpResponse('Invalid request')

core/templates/core/about.html
<!DOCTYPE html>
<html>
<head>
  <title>About Us</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
    }

    header {
      background-color: #333;
      color: #fff;
      padding: 20px;
      text-align: center;
    }

    .container {
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
    }

    h1 {
      font-size: 32px;
      margin-bottom: 20px;
    }

    p {
      line-height: 1.5;
      margin-bottom: 20px;
    }

    .highlight {
      color: #f44336;
      font-weight: bold;
    }

    .team {
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
      align-items: center;
    }

    .team-member {
      width: 300px;
      margin: 20px;
    }

    .team-member img {
      width: 100%;
      border-radius: 50%;
    }

    .team-member h3 {
      font-size: 20px;
      margin-top: 10px;
    }
  </style>
</head>
<body>
  <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
    <div>
    <a href="/" class="text-xl font-semibold">My Course</a>
    <a href="{%url 'core:recommend_ui' %}" class="text-xl font-semibold mx-6 ">Recommend</a>
    </div>

    <div class="space-x-6">
        {%if request.user.is_authenticated%}
        <a href="{%url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log Out</a>
        <a href="{%url 'core:my_learning' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">My Learnings</a>
        {%else%}
        <a href="{%url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
        <a href="{%url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">LogIn</a>
        {%endif%}
    </div>
</nav>
  <header>
    <h1>About Us</h1>
  </header>

  <div class="container p-10">
    <h2 class="text-xl text-bold">Welcome to Course Recommendation System</h2>
    <p>We are passionate about helping individuals discover their educational path and reach their full potential. Our course recommendation system is designed to assist students, professionals, and lifelong learners in finding the right courses that align with their interests, goals, and learning preferences.</p>

    <h2 class="text-xl text-bold mt-2">Our Mission</h2>
    <p>Our mission is to simplify the process of searching and selecting courses by leveraging the power of data and technology. We aim to provide personalized recommendations based on your preferences. By offering tailored course suggestions, we strive to enhance your learning journey and make it more enjoyable and effective.</p>

    <h2 class="text-xl text-bold mt-2">How It Works</h2>
    <p>Our course recommendation system employs algorithms that analyze your learning style. Our system generates a curated list of courses that are most relevant to your needs.</p>

    <h2 class="text-xl text-bold mt-2">Our Team</h2>
    <div class="flex flex-row">
      <div class="team-member">
        <h3>Harshit Bajeta</h3>
        <p>Machine-Learning Engineer</p>
        <p>Front-end developer</p>
      </div>
      <div class="team-member">
        <h3>Ishan Chauhan</h3>
        <p>Back-end Developer</p>
      </div>
      <div class="team-member"> 
        <h3>Ayush Singh</h3>
        <p>Front-end Developer</p>
      </div>
  
      <div class="team-member">
        <h3>Jyoti Bhasin</h3>
        <p>Documentation Specialist</p>
      </div>
     
    </div>
  </div>
</body>
</html>

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss-carousel@0.2.0/dist/carousel.min.css" rel="stylesheet"> -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" /> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/tailwindcss-carousel@0.2.0/dist/carousel.min.js"></script> -->
    <title>{%block title%} {%endblock%} | My Course</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b bg-black text-white">
        <div>
        <a href="/" class="text-xl font-semibold">My Course</a>
        <a href="{%url 'core:recommend_ui' %}" class="text-xl font-semibold mx-6 ">Recommend</a>
        </div>

        <div class="space-x-6">
            {%if request.user.is_authenticated%}
            <a href="{%url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log Out</a>
            <a href="{%url 'core:my_learning' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">My Learnings</a>
            {%else%}
            <a href="{%url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="{%url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">LogIn</a>
            {%endif%}
        </div>
    </nav>
    <div class="px-6 py-6 mx-2 bg-gray-200">
        {%block content%}
        {%endblock%}
    </div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Course recommendation system suggests relevant courses to users based on their preferences, past enrollments, and similar users' choices, improving personalized learning experience and aiding in discovering new educational opportunities.<p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="{%url 'core:about'%}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{%url 'core:contact'%}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                {% comment %} <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li> {% endcomment %}
            </ul>
        </div>
    </footer>
</body>
</html>

core/templates/core/contact.html
<!DOCTYPE html>
<html>
<head>
  <title>Contact Us</title>
  <link rel="stylesheet" href="style.css">
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />
  <style>
    body {
      background-color: gray ;
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    header {
      text-align: center;
      padding: 10px;
    }

    footer {
      background-color: black;
      padding: 20px;
      text-align: center;
      color: white;
    }
  </style>
</head>
<body>
  <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200 bg-black text-white">
    <div>
    <a href="/" class="text-xl font-semibold">My Course</a>
    <a href="{%url 'core:recommend_ui' %}" class="text-xl font-semibold mx-6 ">Recommend</a>
    </div>

    <div class="space-x-6">
        {%if request.user.is_authenticated%}
        <a href="{%url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log Out</a>
        <a href="{%url 'core:my_learning' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">My Learnings</a>
        {%else%}
        <a href="{%url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
        <a href="{%url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">LogIn</a>
        {%endif%}
    </div>
</nav>
  <div class="mt-3 pt-1 bg-grey">
    <h1 class="text-5xl text-center mt-3 my-9"><span class="">Contact</span> Us</h1>
    <div class=" flex flex-row justify-center mr-8">
        <form action="#" class="space-y-5 flex flex-col w-2/4 px-10 py-2">
            <h1 class="text-lg">Send a Message</h1>
            <div class="flex space-x-9">
                <div class="flex flex-col space-y-1 w-1/2">
                    <label for="First Name">First Name</label>
                    <input type="text" name="First" placeholder="John" class="opacity-80 text-black px-1 py-1">
                </div>
                <div class="flex flex-col space-y-1 w-1/2">
                    <label for="Last Name">Last Name</label>
                    <input type="text" name="Last" placeholder="Doe" class="opacity-80 px-1 py-1 text-black">
                </div>
            </div>
            <div class="flex space-x-9">
                <div class="flex flex-col space-y-1 w-1/2">
                    <label for="email">Email</label>
                    <input type="email" name="" placeholder="xyz@gmail.com" required
                        class="opacity-80 px-1 py-1 text-black">
                </div>
                <div class="flex flex-col space-y-1 w-1/2">
                    <label for="Mobile">Mobile No.</label>
                    <input type="text" name="number" placeholder="+91 7998826361"
                        class="opacity-80 px-1 py-1 text-black">
                </div>
            </div>
            <div class="flex flex-col space-y-1 ">
                <label for="message">Message</label>
                <textarea name="message" id="" cols="50" rows="10" placeholder="Enter your text"
                    class="opacity-80 px-1 py-1 text-black"></textarea>
            </div>
            <button
                class="text-left w-1/12 bg-white bg-opacity-60 px-2 py-1 rounded-md hover:bg-opacity-30">Send</button>
        </form>

        <div class=" flex flex-col justify-center ">
            <div class="flex flex-col space-y-3 mx-2 mb-5 px-2  ">
                <h1 class="px-1 text-lg">Info</h1>
                <div class="flex space-x-5 ">
                    <div class=" bg-white rounded-full w-8 h-8 "><i class="fa-solid fa-location-pin px-2 py-2"
                            style="color: black;"></i></div>
                    <h1>Cannaught Palace, New Delhi, India</h1>
                </div>
                <div class="flex space-x-5">
                    <div class="bg-white rounded-full w-8 h-8 flex"><i class="fa-solid fa-envelope px-2 py-2"
                            style="color:black;"></i></div>
                    <a href="gmail.com">xyz1@gmail.com</a>
                </div>
                <div class="flex space-x-5">
                    <div class=" bg-white rounded-full w-8 h-8 flex"><i class="fa-solid fa-phone px-2 py-2"
                            style="color:black;"></i></div>
                    <h1>+91 8556873190</h1>
                </div>
                <div class="flex space-x-6 pt-6 pb-3 px-1">
                    <div class="  rounded-full w-8 h-8 "><i class="fa-brands fa-facebook-f px-2 py-2"
                            style="color: black;"></i></div>
                    <div class="  rounded-full w-8 h-8 "><i class="fa-brands fa-twitter px-2 py-2"
                            style="color:black;"></i></div>
                    <div class="  rounded-full w-8 h-8 "><i class="fa-brands fa-instagram px-2 py-2"
                            style="color:black;"></i></div>
                    <div class="  rounded-full w-8 h-8 "><i class="fa-brands fa-linkedin px-2 py-2"
                            style="color:black;"></i></div>
                </div>
            </div>
            <div class="mx-2 px-2">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d14008.114947263992!2d77.19734799110624!3d28.628900818956115!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1scannot%20place!5e0!3m2!1sen!2sin!4v1680381829385!5m2!1sen!2sin"
                    width="400" height="250" style="border:0;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>
</div>

 

  <footer>
    <p>&copy; 2023 Course Recommendation System. All rights reserved.</p>
  </footer>
</body>
</html>

core/templates/core/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss-carousel@0.2.0/dist/carousel.min.css" rel="stylesheet"> -->
    <script src="https://cdn.tailwindcss.com"></script>
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> {% endcomment %}

    <!-- <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" /> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/tailwindcss-carousel@0.2.0/dist/carousel.min.js"></script> -->
    <!-- Latest compiled and minified CSS -->
</head>
<body>
    <nav class="py-3 px-6 flex justify-between items-center bg-black text-white">
        <div>
        <a href="/" class="text-xl font-semibold">My Course</a>
        <a href="{%url 'core:recommend_ui' %}" class="text-xl font-semibold mx-6 ">Recommend</a>
        </div>

        <div class="space-x-6">
            {%if request.user.is_authenticated%}
            <a href="{%url 'core:logout' %}" class="px-6 py-2  font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log Out</a>
            <a href="{%url 'core:my_learning' %}" class="px-6 py-2 font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">My Learnings</a>
            {%else%}
            <a href="{%url 'core:signup' %}" class="px-6 py-2  font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="{%url 'core:login' %}" class="px-6 py-2  font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">LogIn</a>
            {%endif%}
        </div>
    </nav>

    <h1 class="text-5xl my-[2%] text-center">Error</h1>
    <p class="text-center text-xl">{{ message }}</p>
</body>
</html>