core/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('my_learning', views.learning, name='my_learning'),
    path('recommend/', views.recommend_ui, name='recommend_ui'),
    path('recommend_books/', views.recommend, name='recommend'),
    # path('face_authentication/', views.face_authentication, name='face_authentication'),
]

course_recommendation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

item/urls.py
from django.urls import path, include
from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

item/models.py
from django.db import models
# from django.contrib.auth.models import User
# from core.models import CustomUser

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items' ,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    img = models.ImageField(upload_to='item_images', blank=True, null=True)

    def __str__(self) -> str:
        return self.name

item/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item
from core.models import Order, Order_Item, User
# from django.contrib.auth.models import User

# Create your views here.
def detail(request, pk):

    item = get_object_or_404(Item, pk=pk)
    customer = User.objects.filter(username=request.user.username)[0]
    order = Order.objects.filter(user = customer)[0]

    related_items = Item.objects.filter(category = item.category).exclude(pk=pk)[0:3]

    a = dict()
    
    if request.method == 'POST':
        order_item = Order_Item(order = order, item = item)
        order_item.save()
        items = Order_Item.objects.filter(order=order)
        a['items'] = items
        return render(request, 'core/cart.html',context=a)
    
    a['item'] = item
    a['related_items'] = related_items

    order_item = Order_Item.objects.filter(order=order, item=item)

    if order_item.exists():
        a['bought'] = True
    else:
        a['bought'] = False
    
    return render(request, 'item/detail.html',context=a)

item/templates/item/detail.html
{% extends 'core/base.html'%}

{%block title%}
{{item.name}}
{%endblock%}

{%block content%}
<div class="grid grid-cols-5 gap-6">

    <div class="col-span-3">
        <img src="{{item.img.url}}" alt="img1" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{item.name}}</h1>
        <p class="text-gray-500"><strong>Price: </strong>₹{{item.price}}</p>

        {%if item.description%}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description</strong><br>
            {{item.description}}
        </p>
        {%endif%}

        <form action="." method="post">
            {%csrf_token%}
            {%if bought%}
            <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Go to Course</a>
            {%else%}
            <button type="submit" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">BUY</button>
            {%endif%}
        </form>
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Courses</h2>
    <div class="grid grid-cols-3 gap-3">
        {%for item in related_items%}
        <div class="border-2">
            <a href="{%url 'item:detail' item.id%}">
                <div class="flex justify-center">
                    <img src="{{item.img.url}}" alt="img1" class="rounded-t-xl" style="height: 250px; width: 70%;">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{item.name}}</h2>
                    <p class="text-gray-500">Price: ₹{{item.price}}</p>
                </div>
            </a>
        </div>
        {%endfor%}
    </div>
</div>

{%endblock%}